config/routes.rb
Parcelid::Application.routes.draw do
  get "welcome/index"
  root "welcome#index"
  
resources :properties do
	resources :stories do
		resources :comments
end
end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :story
end

app/models/property.rb
class Property < ActiveRecord::Base

	has_many :stories
	
	extend ::Geocoder::Model::ActiveRecord

	def full_address
		[address, city, state, zip].compact.join(', ')
	end
	geocoded_by :full_address

	after_validation :geocode

	def self.search(search)
		if search 
			find(:all, :conditions => ['city LIKE ?', "%#{search}%"])
		else
			find(:all)
		end
	end
end

app/models/story.rb
class Story < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	
	belongs_to :property
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def new
		@property = Property.find(params[:property_id])
		@story = @property.stories.find(params[:story_id])
		@comment = @property.stories.comments.new
	end



	def create
		@property = Property.find(params[:property_id])
		@story = @property.stories.find(params[:story_id])
		@comment = @story.comments.create(comment_params)
		
		redirect_to property_path(@property)
	end

	def destroy
		@story = Story.find(params[:story_id])
		@comment = @story.comments.find(params[:id])
		@comment.destroy
		redirect_to story_path(@story)
	end

private
def comment_params
	params.require(:comment).permit(:commenter, :body, :story_id)
end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

def index
	@properties = Property.search(params[:search])

end

def new
	@property = Property.new
end
def create
	@property = Property.new(property_params)
	@property.save
	redirect_to @property
end
def show
	@property = Property.find(params[:id])
	
	
end
def edit
	@property = Property.find(params[:id])
end

def update
	@property = Property.find(params[:id])
	if @property.update(params[:property].permit(:address, :address_2, :city, :state, :zip, :name, :county, :neighborhood))
		redirect_to @property
	else
		render 'edit'
	end
end


private
def property_params
	params.require(:property).permit(:address, :address_2, :city, :state, :zip, :name, :county, :neighborhood, :property_id, :story_type, :latitude, :longitude)
end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
	
	def new
		@property = Property.find(params[:property_id])
		@story = @property.stories.new
	end


	def create
		@property = Property.find(params[:property_id])

		@story = @property.stories.create(story_params)
		@story = Story.new(story_type: 2)
		if @story.save
			redirect_to property_path(@property)
		else
			flash[:error] = "Problem!"
			redirect_to property_path(@property)
		end
	end

	def edit
		@property = Property.find(params[:property_id])
		@story = @property.stories.find(params[:id])
	end

	def update
		@property =Property.find(params[:property_id])
		@story = @property.stories.find(params[:id])

		if @story.update(story_params)
			redirect_to property_path(@property)

		else
			render 'edit'
		end
	end


	def destroy
		@property = Property.find(params[:property_id])
		@story = @property.stories.find(params[:id])
		@story.destroy
		redirect_to property_path(@property)
	end

private
def story_params
	params.require(:story).permit(:story_type, :when, :title, :description, :source, :property_id)
end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<p>
	<strong>Commenter:</strong>
	<%= comment.commenter %>
</p>
<p>
	<strong>Comment:</strong>
	<%= comment.body %>
</p>
<p>
<%= link_to 'Destroy Comment', [comment.story, comment], method: :delete, data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@story, @story.comments.build]) do |f| %>
	<p>
		<%= f.label :commenter %><br>
		<%= f.text_field :commenter %>
	</p>
	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body %>
	</p>
	<p>
		<%= f.submit %>
	</p>
	<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <title>parcelid</title>
      <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
      <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
      <%= csrf_meta_tags %>
    </head>
  <body>
  	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
         
         <li><%=link_to "Home", welcome_index_path %></li>
         <li><%= link_to "Map", properties_path %></li>
        </ul>
        
        <ul class="nav navbar-nav navbar-right">
        </ul>
      </div><!-- /.navbar-collapse -->
    </nav>
    <header>
      <div class="heading"><h1>parcelID<a href="#"></a><br><small>Discover your home's story.</small></h1></div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
    <br>
    <br>
    <footer>
      <p>&copy; ParcelID 2013</p>
    </footer>
  </body>
</html>

app/views/properties/edit.html.erb
<div class="row">
	<div class="col-xs-12 col-sm-6 col-md-8">
		<h1>New Property</h1>
		<%= form_for :property, url: property_path(@property), :html => {:class => "form-horizontal"}, method: :patch do |f| %>
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Address</h3>
			</div>
			<div class="panel-body">
				<div class="form-group">
					<div class="col-sm-2 control-label"><%= f.label :address, "Address" %></div>
					<div class="col-sm-10"><%= f.text_field :address, :class => 'form-control' %></div>
				</div>
				<div class="form-group">
					<div class="col-sm-2 control-label"><%= f.label :address_2, "Address 2" %></div>
					<div class="col-sm-10"><%= f.text_field :address_2, :class => 'form-control' %></div>
				</div>
				<div class="form-group">
					<div class="col-sm-2 control-label"><%= f.label :city, "City" %></div>
					<div class="col-sm-10"><%= f.text_field :city, :class => 'form-control' %></div>
				</div>
				<div class="form-group">
					<div class="col-sm-2 control-label"><%= f.label :State, "State" %></div>
					<div class="col-sm-10"><%= f.text_field :state, :class => 'form-control' %></div>
				</div>
				<div class="form-group">
					<div class="col-sm-2 control-label"><%= f.label :zip, "Zip" %></div>
					<div class="col-sm-10"><%= f.text_field :zip, :class => 'form-control' %></div>
				</div>
			</div>
		</div>
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Basic Information</h3>
				</div>
				<div class="panel-body">
					<div class="form-group">
						<div class="col-sm-2 control-label"><%= f.label :name, "Name" %></div>
						<div class="col-sm-10"><%= f.text_field :name, :class => 'form-control'%></div>
					</div>

					<div class="form-group">
						<div class="col-sm-2 control-label"><%= f.label :neighborhood, "Neighborhood" %></div>
						<div class="col-sm-10"><%= f.text_field :neighborhood, :class => 'form-control' %></div>
					</div>
					<div class="form-group">
						<div class="col-sm-2 control-label"><%= f.label :county, "County" %></div>
						<div class="col-sm-10"><%= f.text_field :county, :class => 'form-control' %></div>
					</div>
				</div>
			</div>
			<%= f.submit "Add", :class => 'btn btn-red btn-lg' %>
		<% end %>
	</div>
	
	<div class="col-xs-6 col-md-4"></div>
</div>


	

app/views/properties/index.html.erb
<!--  start Google maps code -->
  <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBUt9keauvaYZOxOlddq6PLkSsuqbH-tn4&sensor=true">
  </script>
  <script type="text/javascript">



    function initialize() {

      var mapOptions = {
        center: new google.maps.LatLng(38.376115, -97.844667),
        zoom: 4,
        mapTypeId:google.maps.MapTypeId.HYBRID
      };

        var map = new google.maps.Map(document.getElementById("map-canvas"),
        mapOptions);

    // To add many markers to array to the map, use the 'map' property
                   
      var myMarkers = [];
        <% @properties.each do |p| %>
        myMarkers.push(new google.maps.LatLng(<%= p.latitude %>, <%= p.longitude %>));
        <% end %>

      var i, newMarker;
        for (i = 0; i < myMarkers.length; i++) {
          newMarker = new google.maps.Marker({
            position: (myMarkers[i]),
            map: map,
            draggable: true
          });

        newMarker.setVisible(true);
        }
    }
  //  end of initialize
      google.maps.event.addDomListener(window, 'load', initialize);


  </script>
<!-- end Google Maps code -->
<div class="filter-bar row">
  <%= form_tag properties_path, :method => 'get' do %>
  <div class="col-sm-1 search-label">Find a property.
  </div>
  <div class="col-sm-4 search-box"><%= text_field_tag :search, params[:search], placeholder: "e.g. Los Angeles, Miami, New York", :class => 'form-control' %>
  </div>
  <div class="clearfix visible-xs"></div>
  
  <div class="col-sm-3"><%= submit_tag "Search by city", :city => nil, :class => "btn btn-default btn-lg" %>
  </div>
  <% end %>
  <div class="col-sm-4 filter-right">
    <a> <%= link_to "Add a property »", new_property_path, :class => 'btn btn-red btn-lg' %></a>
  </div>
</div>
<div id= "map-canvas"></div>
<div class="media"> 
  	<% @properties.each do |property| %>
  	<div class="media-body well">
  	  <h4 class="media-heading"><%= link_to(property.address, "/properties/#{property.id}") %><%= property.address_2 %></h4>
    		<%= property.city %>
    		<%= property.state %>
    		<%= property.zip %>
  	</div>
	<% end %>
</div>
		



 

app/views/properties/new.html.erb
<div class="row">
	<div class="col-xs-12 col-sm-6 col-md-8">
		<h1>New Property</h1>
		<%= form_for @property, :html => {:class => "form-horizontal"} do |f| %>
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Address</h3>
				</div>
				<div class="panel-body">
					<div class="form-group">
						<div class="col-sm-2 control-label"><%= f.label :address, "Address" %></div>
						<div class="col-sm-10"><%= f.text_field :address, :class => 'form-control' %></div>
					</div>
					<div class="form-group">
						<div class="col-sm-2 control-label"><%= f.label :address_2, "Address 2" %></div>
						<div class="col-sm-10"><%= f.text_field :address_2, :class => 'form-control' %></div>
					</div>
					<div class="form-group">
						<div class="col-sm-2 control-label"><%= f.label :city, "City" %></div>
						<div class="col-sm-10"><%= f.text_field :city, :class => 'form-control' %></div>
					</div>
					<div class="form-group">
						<div class="col-sm-2 control-label"><%= f.label :State, "State" %></div>
						<div class="col-sm-10"><%= f.text_field :state, :class => 'form-control' %></div>
					</div>
					<div class="form-group">
						<div class="col-sm-2 control-label"><%= f.label :zip, "Zip" %></div>
						<div class="col-sm-10"><%= f.text_field :zip, :class => 'form-control' %></div>
					</div>
				</div>
			</div>
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Basic Information</h3>
				</div>
				<div class="panel-body">
					<div class="form-group">
						<div class="col-sm-2 control-label"><%= f.label :name, "Name" %></div>
						<div class="col-sm-10"><%= f.text_field :name, :class => 'form-control'%></div>
					</div>
					<div class="form-group">
						<div class="col-sm-2 control-label"><%= f.label :neighborhood, "Neighborhood" %></div>
						<div class="col-sm-10"><%= f.text_field :neighborhood, :class => 'form-control' %></div>
					</div>
					<div class="form-group">
						<div class="col-sm-2 control-label"><%= f.label :county, "County" %></div>
						<div class="col-sm-10"><%= f.text_field :county, :class => 'form-control' %></div>
					</div>
				</div>
			</div>
			<%= f.submit "Add", :class => 'btn btn-red btn-lg' %>
		<% end %>
	</div>
	<div class="col-xs-6 col-md-4">
	</div>
</div>


	

app/views/properties/show.html.erb
<!--  start Google maps code -->
<script type="text/javascript"
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBUt9keauvaYZOxOlddq6PLkSsuqbH-tn4&sensor=false">
</script>
<script type="text/javascript">



  function initialize() {
    var myLatLng = new google.maps.LatLng(<%= @property.latitude %>,<%= @property.longitude %>);
    var mapOptions = {
      center: myLatLng,
      zoom: 20,
      mapTypeId:google.maps.MapTypeId.HYBRID
    };

      var map = new google.maps.Map(document.getElementById("map-canvas"),
      mapOptions);


  // To add the marker to the map, use the 'map' property
    
      var marker = new google.maps.Marker({
       position: myLatLng,
        map:map,
         draggable:true,
        animation:google.maps.Animation.DROP,
      });
      
  }

      //  end of initialize
      google.maps.event.addDomListener(window, 'load', initialize);

</script>
<!-- end Google Maps code -->



<!-- Modal -->
<!-- Button trigger modal -->

<button class="btn btn-red btn-lg"  id="modal-button" data-toggle="modal" data-target="#myModal"><strong><%= @property.name %></strong><br><%= @property.address %> <%= @property.address_2 %><br><%= @property.city %>, <%=@property.state %>  <%= @property.zip %>
</button>

<div id="map-canvas"></div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-storyheader" id="story-details">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel"></h4>
        <ul class="nav nav-tabs">
            <li class="active"><a href="#details" data-toggle="tab">Details</a></li>
            <li><a href="#timeline" data-toggle="tab">Timeline</a></li>
            <li><a href="#story" data-toggle="tab">Add a story</a></li>
        </ul>
      </div>
      <div class="modal-body">
        <div class="tab-content properties-information">
          <div class="tab-pane active" id="details">
            <div class="row">
              <div class="left-details col-md-4">
                <div class="address-details"><strong><%= @property.name %><br><%= @property.address %> <%= @property.address_2 %><%= @property.city %>, <%=@property.state %>  <%= @property.zip %></strong><br><%= @property.neighborhood %> <%= @property.county %>
                </div>
                <div class='btn btn-default btn-xs'><%= link_to 'Edit Property Details', edit_property_path(@property) %>
                </div>
              </div>
              <div class="col-md-8">
                  <% @property.stories.where(:story_type => [2]).each do |story| %>
                  <ul class="media-list">
                    <li class="media">
                      <div class="media-body">
                          <h4 class="media-heading"></h4>
                            <blockquote>
                              <p><%= story.when %></p>
                              <p><%= story.description %></p>
                              <small><cite title="Source Title"><%= story.source %></cite></small>
                            </blockquote>
                          <%= link_to 'Delete Story', [story.property, story],  method: :delete, data: { confirm: 'Are you sure?' }, :class => 'pull-right btn btn-default btn-xs' %>
                      </div>
                    </li>
                  </ul>
                  <% end %>
              </div>
            </div>
          </div>
            <div class="tab-pane" id="timeline">
              <% @property.stories.where(:story_type => [1]).each do |story| %>
              <ul class="media-list">
                <li class="media">  
                  <div class="media-body well">
                    <div class="media-heading"><p><%= link_to 'Delete Story', [story.property, story],  method: :delete, data: { confirm: 'Are you sure?' }, :class => 'pull-right btn btn-default btn-xs' %></p><%= story.when %>
                    </div>
                    <p><%= story.description %></p>
                    <p><small>Source: <%= story.source %></small></p>    
                </div>
                </li>
              </ul>
              <% end %>
            </div>
          <div class="tab-pane" id="story">
            <div class="form-horizontal"><%= form_for ([@property, @property.stories.build]) do |f| %>
              <div class="well"> Do you have a story to add? Please select: <%= select(:story, :story_type, [['Event', 1], ['Fact', 2]]) %></div>
              <div class="form-group">
                <div class="col-sm-2 control-label"><%= f.label :when, "Date of Story" %></div>
                <div class="col-sm-10"><%= f.date_field :when, :class => 'form-control' %></div>
              </div>
              <div class="form-group">
                <div class="col-sm-2 control-label"><%= f.label :description, "Description" %></div>
                <div class="col-sm-10"><%= f.text_area :description, :class => 'form-control' %></div>
              </div>
              <div class="form-group">
                <div class="col-sm-2 control-label"><%= f.label :source, "Source url" %></div>
                <div class="col-sm-10"><%= f.text_field :source, :class => 'form-control' %></div>
              </div>
              <div class="form_add"><%= f.submit "Add", :class => 'btn btn-default btn-lg' %>
              </div>
                <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer"></div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

        



        

app/views/stories/edit.html.erb
<div class="form-horizontal"><%= form_for([@property, @property.stories]), method: :patch do |f| %>
  <div class="well"> Do you have a story to add? Please select: <%= select(:story, :story_type, [['Event', 1], ['Fact', 2]]) %>
  </div>
  <div class="form-group">
   <div class="col-sm-2 control-label"><%= f.label :when, "Date of Story" %></div>
   <div class="col-sm-10"><%= f.date_field :when, :class => 'form-control' %></div>
  </div>
  <div class="form-group">
    <div class="col-sm-2 control-label"><%= f.label :description, "Description" %></div>
    <div class="col-sm-10"><%= f.text_area :description, :class => 'form-control' %></div>
  </div>
  <div class="form-group">
    <div class="col-sm-2 control-label"><%= f.label :source, "Source url" %></div>
    <div class="col-sm-10"><%= f.text_field :source, :class => 'form-control' %></div>
  </div>
</div>
<div class="form_add"><%= f.submit "Add", :class => 'pull-right btn btn-default btn-lg ' %>
</div>
<% end %>

app/views/stories/new.html.erb
<%= render "stories/form" %>

app/views/welcome/index.html.erb
    <div class="container">
      <div class="jumbotron">
        <h1>Welcome to parcelID</h1>
        <p>Search for a place you have lived and add a story. Discover stories about places you have been. Help solve a home history mistery.</p>
        <p><a> <%= link_to "Search Properties »", properties_path, :class => 'btn btn-red btn-lg' %></a></p>
      </div>
    </div>
    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Research</h2>
          <p>Research your home's story. </p>
         
        </div>
        <div class="col-md-4">
          <h2>Record</h2>
          <p>Add stories to places you have been. </p>
         
       </div>
        <div class="col-md-4">
          <h2>Discover</h2>
          <p>Discover who else has lived where you have lived.</p>
         
        </div>
      </div>

      <hr>
    </div>